name: Deploy new entries to Cloudflare Workers

on:
  push:
    branches:
      - main
    paths:
      - "assets/static/data/*.json"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
      - name: Deploy to Cloudflare Workers
        uses: cloudflare/wrangler-action@2.0.0
        with:
          # TODO: the secrets are not set yet in GitHub
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
